[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38", "py39"]
extend-exclude = '''
(
    template/
)
'''

[tool.isort]
profile = "black"
